language: java
sudo: false #faster builds

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
#  - ./gradlew stage

cache:
  directories:
    - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash) -t a45dd7b6-d02d-41ce-ae1a-692f280c029a